# Generated by Django 6.0.2 on 2026-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_break1_added_attendance_break2_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
