# Generated by Django 6.0.2 on 2026-03-04 11:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_on_break',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_sessions', to='core.attendance')),
            ],
        ),
    ]
