"""
Django settings for etams project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-11sf&=@6c@2de_ocou4fg-^=t^=7&q-*o)q8f@2oo$!ce&k1ae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
     'jazzmin',  
     'core',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'etams.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'etams.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'employee_db',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



JAZZMIN_SETTINGS = {
    "site_title": "ETAMS Admin",
    "site_header": "ETAMS",
    "site_brand": "ETAMS Admin",
    "welcome_sign": "Welcome to ETAMS Admin Panel",
    "copyright": "ETAMS",

    "show_sidebar": True,
    "navigation_expanded": True,

    # ⭐ Top Header Menu (Added Logout Button)
    "topmenu_links": [
        
            {
    "name": "Logout",
    "url": "/admin-logout/",
    "icon": "fas fa-sign-out-alt",
},
    ],

    # Side menu ordering
    "order_with_respect_to": [
        "core",
        "core.Employee",
        "core.Department",
        "core.Attendance",
        "core.Task",
        "auth",
    ],

    # Custom grouped links
    "custom_links": {
        "core": [
            {
                "name": "HR • Employees",
                "url": "/admin/core/employee/",
                "icon": "fas fa-user-tie",
            },
            {
                "name": "HR • Departments",
                "url": "/admin/core/department/",
                "icon": "fas fa-building",
            },
            {
                "name": "Attendance • Logs",
                "url": "/admin/core/attendance/",
                "icon": "fas fa-calendar-check",
            },
            {
                "name": "Tasks • All Tasks",
                "url": "/admin/core/task/",
                "icon": "fas fa-tasks",
            },
        ]
    },

    "icons": {
        "core": "fas fa-layer-group",
        "core.Department": "fas fa-building",
        "core.Employee": "fas fa-user-tie",
        "core.Attendance": "fas fa-calendar-check",
        "core.Task": "fas fa-tasks",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    "show_ui_builder": True,
}

 
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
}
USE_TZ = True
TIME_ZONE = "Asia/Kolkata"
